defaults: &DEFAULTS

  # ECS connection parameters
  ecs:
    # Should always be a secure connection via https
    url: https://ecs.localhost
    # basic auth credentials
    login: ecs-login-name
    password: ecs-password
    # Uncomment next line if yoy want to serve the password via environment variable (security)
    #password: <%= ENV['ECS_PASSWORD'] %>
    #
    # Uncomment next line if your ECS-Server-Certificate is signed by a local CA.
    #ssl_ca_file: /path/to/local-root-ca.crt.pem
    #
    # verify ECS server certificate
    # Comment next line if ecs->url scheme is not https which is a very bad idea in respect of security
    verify_ssl: true


  ###
  ### normally you won't need to change anything after here
  ###

  servicename: ViP merge and compute

  # set to false if you want to make your http calls to ECS directly
  # or set it to a proxy url like http://proxy.example.com:7888
  # The default is using no proxy.
  # proxy: http://localhost:3128
  proxy: false

  # valid debug levels: debug, info, error
  debug_level: debug

  # mapping of resource names
  resources:
    servicename: numlab
    sys_events:
      pretty_print: false
      name: sys/events
    sys_memberships:
      pretty_print: false
      name: sys/memberships
    evaluationjobs:
      pretty_print: false
      name: numlab/evaluation_jobs
    results:
      pretty_print: false
      name: numlab/results
    points:
      pretty_print: false
      name: numlab/points
    exercises:
      pretty_print: false
      name: numlab/exercises
    solutions:
      pretty_print: false
      name: numlab/solutions
    evaluations:
      pretty_print: false
      name: numlab/evaluations
    points:
      pretty_print: false
      name: numlab/points

  # mapping known event-types
  # only these event-types trigger some action
  eventtypes:
    job:
      name: numlab/evaluation_jobs
    result:
      name: numlab/results


development:
  <<: *DEFAULTS

test:
  <<: *DEFAULTS

production:
  <<: *DEFAULTS
  # valid debug levels: debug, info, error
  debug_level: info
